//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public decimal CEDULA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string CORREO { get; set; }
        public decimal TELEFONO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string ROL { get; set; }
    }
}
