//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.TRANSPORTISTA = new HashSet<TRANSPORTISTA>();
        }
    
        public decimal ID_VEHICULO { get; set; }
        public decimal PLACA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string COLOR { get; set; }
        public decimal ID_TIPO { get; set; }
    
        public virtual TIPO_VEHICULO TIPO_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSPORTISTA> TRANSPORTISTA { get; set; }
    }
}
